### ISSUE TITLE
Error: TSDB: Timestamp cannot be older than the latest timestamp in the time series

### ISSUE THREAD

**Issue by awaili** [RedisTimeSeries/redistimeseries-go#36]
because the data can't be arrived sequentially, the  problem is I can't  write the data if the newer timer been written, how can I solve this ?

**Comment by gkorland** [comment]
The current implementation doesn't support out of order append.

**Comment by filipecosta90** [comment]
hi there @awaili, closing this issue ( since it is out of the scope of the client ) and keeping a reference to the RedisTimeSeries repo issue that answers this question, so that anyone who reaches here is pointed towards the most up to date discussion.  
https://github.com/RedisTimeSeries/RedisTimeSeries/issues/96
